const EVENT = {
  title: "LOTOS",
  subtitle: "Итоги ивента",
  cover: "img/cover.jpg",
  stats: ""
};

const WORKS = [
  {
    id: 1,
    username: "@forLansely",
    characters: "Астерия",
    title: "Работа #1",
    image: "img/works/work_001.jpg",
    postLink: "https://t.me/StableWaifuComments/17767675",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 2,
    username: "@Seraphimss",
    characters: "Астерия",
    title: "Работа #2",
    image: "img/works/work_002.jpg",
    postLink: "https://t.me/StableWaifuComments/17767971",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 3,
    username: "@Seraphimss",
    characters: "Астерия",
    title: "Работа #3",
    image: "img/works/work_003.jpg",
    postLink: "https://t.me/StableWaifuComments/17767978",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 4,
    username: "@Seraphimss",
    characters: "Астерия, Эриду",
    title: "Работа #4",
    image: "img/works/work_004.jpg",
    postLink: "https://t.me/StableWaifuComments/17767985",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 5,
    username: "@ChrezDev",
    characters: "Таласса",
    title: "Работа #5",
    image: "img/works/work_005.jpg",
    postLink: "https://t.me/StableWaifuComments/17768874",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 6,
    username: "@crystalloli",
    characters: "Эриду",
    title: "Работа #6",
    image: "img/works/work_006.jpg",
    postLink: "https://t.me/StableWaifuComments/17769442",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 7,
    username: "@crystalloli",
    characters: "Кассиан",
    title: "Работа #7",
    image: "img/works/work_007.jpg",
    postLink: "https://t.me/StableWaifuComments/17769671",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 8,
    username: "@venera_chan",
    characters: "Астерия",
    title: "Работа #8",
    image: "img/works/work_008.jpg",
    postLink: "https://t.me/StableWaifuComments/17770983",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 9,
    username: "@the_elv",
    characters: "Дандан Цзянь",
    title: "Работа #9",
    image: "img/works/work_009.jpg",
    postLink: "https://t.me/StableWaifuComments/17771291",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 10,
    username: "@venera_chan",
    characters: "Лагострёмия",
    title: "Работа #10",
    image: "img/works/work_010.jpg",
    postLink: "https://t.me/StableWaifuComments/17771353",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 11,
    username: "@venera_chan",
    characters: "Лагострёмия",
    title: "Работа #11",
    image: "img/works/work_011.jpg",
    postLink: "https://t.me/StableWaifuComments/17772036",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 12,
    username: "@venera_chan",
    characters: "Астерия",
    title: "Работа #12",
    image: "img/works/work_012.jpg",
    postLink: "https://t.me/StableWaifuComments/17773566",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 13,
    username: "Азизбек",
    characters: "Кассиан",
    title: "Работа #13",
    image: "img/works/work_013.jpg",
    postLink: "https://t.me/StableWaifuComments/17774692",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 14,
    username: "Азизбек",
    characters: "Иона Карлосс",
    title: "Работа #14",
    image: "img/works/work_014.jpg",
    postLink: "https://t.me/StableWaifuComments/17774740",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 15,
    username: "Азизбек",
    characters: "Эриду",
    title: "Работа #15",
    image: "img/works/work_015.jpg",
    postLink: "https://t.me/StableWaifuComments/17774831",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 16,
    username: "Азизбек",
    characters: "Лагострёмия",
    title: "Работа #16",
    image: "img/works/work_016.jpg",
    postLink: "https://t.me/StableWaifuComments/17774896",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 17,
    username: "Азизбек",
    characters: "Таласса",
    title: "Работа #17",
    image: "img/works/work_017.jpg",
    postLink: "https://t.me/StableWaifuComments/17774941",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 18,
    username: "Азизбек",
    characters: "Церера",
    title: "Работа #18",
    image: "img/works/work_018.jpg",
    postLink: "https://t.me/StableWaifuComments/17774980",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 19,
    username: "Азизбек",
    characters: "Эриду, Церера",
    title: "Работа #19",
    image: "img/works/work_019.jpg",
    postLink: "https://t.me/StableWaifuComments/17775030",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 20,
    username: "Азизбек",
    characters: "Эриду",
    title: "Работа #20",
    image: "img/works/work_020.jpg",
    postLink: "https://t.me/StableWaifuComments/17775087",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 21,
    username: "Азизбек",
    characters: "Астерия",
    title: "Работа #21",
    image: "img/works/work_021.jpg",
    postLink: "https://t.me/StableWaifuComments/17775221",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 22,
    username: "@DBcrimson",
    characters: "Иона Карлосс",
    title: "Работа #22",
    image: "img/works/work_022.jpg",
    postLink: "https://t.me/StableWaifuComments/17775269",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 23,
    username: "Азизбек",
    characters: "Мао Цзи",
    title: "Работа #23",
    image: "img/works/work_023.jpg",
    postLink: "https://t.me/StableWaifuComments/17775405",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 24,
    username: "@DBcrimson",
    characters: "Дандан Цзянь",
    title: "Работа #24",
    image: "img/works/work_024.jpg",
    postLink: "https://t.me/StableWaifuComments/17775518",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 25,
    username: "@venera_chan",
    characters: "@forLansely 3 Приятная работа, стилистика, да и сама атмосфера. Она ощущается такой куколкой. Очень мило",
    title: "Работа #25",
    image: "img/works/work_025.jpg",
    postLink: "https://t.me/StableWaifuComments/17776529",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 26,
    username: "Азизбек",
    characters: "@Seraphimss 3 Явно после длительного полёта. Вон, как зыркает",
    title: "Работа #26",
    image: "img/works/work_026.jpg",
    postLink: "https://t.me/StableWaifuComments/17777049",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 27,
    username: "@macsheacaich",
    characters: "@Seraphimss 4 Выпить после тяжёлого дня, очень приятно. Но не хватает наглой улыбки как по мне",
    title: "Работа #27",
    image: "img/works/work_027.jpg",
    postLink: "https://t.me/StableWaifuComments/17778508",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 28,
    username: "@macsheacaich",
    characters: "@Seraphimss 4 Подружки решили впэмечте посидеть и пообщаться. Эриду тут даже ничего не чудит.",
    title: "Работа #28",
    image: "img/works/work_028.jpg",
    postLink: "https://t.me/StableWaifuComments/17790155",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 29,
    username: "@desu_chaan",
    characters: "@ChrezDev 5 Очень красивая работа, я в неё влюбилась почти сразу. Так нежно и красиво вышло, эта вода, танцующая поза, ночь. Все прям шикарно!",
    title: "Работа #29",
    image: "img/works/work_029.jpg",
    postLink: "https://t.me/StableWaifuComments/17787254",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 30,
    username: "@crystalloli",
    characters: "@crystalloli 4 Я ждала, что кто-то сделает такую двойтвенность природы Эриду, но не думала, что это будет так быстро. Вышло красиво, сочно.",
    title: "Работа #30",
    image: "img/works/work_030.jpg",
    postLink: "https://t.me/StableWaifuComments/17784943",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 31,
    username: "@Pixe1m4n",
    characters: "@crystalloli 4 Уютная работа. Рысёнок выдимо слишком ушёл в себя, что начал кусать свой хвост",
    title: "Работа #31",
    image: "img/works/work_031.jpg",
    postLink: "https://t.me/StableWaifuComments/17784652",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 32,
    username: "Азизбек",
    characters: "@venera_chan 5 и снова шикарная работа. Сама малышка за своей работой, но слегка отвлеклась на звездочку",
    title: "Работа #32",
    image: "img/works/work_032.jpg",
    postLink: "https://t.me/StableWaifuComments/17784459",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 33,
    username: "@Podpolniy_Krisich",
    characters: "@the_elv 4 Очень много красного, но ей подходит такое. Еще и шприц в руках держит",
    title: "Работа #33",
    image: "img/works/work_033.jpg",
    postLink: "https://t.me/StableWaifuComments/17784003",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 34,
    username: "@macsheacaich",
    characters: "@venera_chan 4 Наглая Лаг на машине. Еще и смотрит, как на говно. Прикольно",
    title: "Работа #34",
    image: "img/works/work_034.jpg",
    postLink: "https://t.me/StableWaifuComments/17784415",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 35,
    username: "Азизбек",
    characters: "@venera_chan 2 Тут не шибко понравилась меша, но сама работа вышла вайбовой и атмосферной.",
    title: "Работа #35",
    image: "img/works/work_035.jpg",
    postLink: "https://t.me/StableWaifuComments/17784352",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 36,
    username: "@ShriMpik1",
    characters: "@venera_chan 3 Я не очень люблю пирсинг на сосках, но сама работа выглядит хорошо и сочно",
    title: "Работа #36",
    image: "img/works/work_036.jpg",
    postLink: "https://t.me/StableWaifuComments/17784023",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 37,
    username: "@Podpolniy_Krisich",
    characters: "Азизбек 3 грустный Арт. И правда печально, что ты по сути потерял дом, хоть ты и никогда в нем не жил, и вся твоя жизнь ограничена летающий",
    title: "Работа #37",
    image: "img/works/work_037.jpg",
    postLink: "https://t.me/StableWaifuComments/17783749",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 38,
    username: "@macsheacaich",
    characters: "Азизбек 2 Потеря дома, и самого себя, оставляет на каждом, свой непоправимый след",
    title: "Работа #38",
    image: "img/works/work_038.jpg",
    postLink: "https://t.me/StableWaifuComments/17783772",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 39,
    username: "@venera_chan",
    characters: "Азизбек 4 Мне очень понравилась сама меша.",
    title: "Работа #39",
    image: "img/works/work_039.jpg",
    postLink: "https://t.me/StableWaifuComments/17783690",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 40,
    username: "Азизбек",
    characters: "Азизбек 5 Очень страшно, когда на тебе лежит страшная ответственность. Ты не просто следишь за состоянием города-космолёта, ты поддерживаешь его",
    title: "Работа #40",
    image: "img/works/work_040.jpg",
    postLink: "https://t.me/StableWaifuComments/17783170",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 41,
    username: "Азизбек",
    characters: "Азизбек 2 Ну, прикольно, магичка-рыба",
    title: "Работа #41",
    image: "img/works/work_041.jpg",
    postLink: "https://t.me/StableWaifuComments/17783039",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 42,
    username: "@macsheacaich",
    characters: "Азизбек 2 Эдакое городское, прикольно",
    title: "Работа #42",
    image: "img/works/work_042.jpg",
    postLink: "https://t.me/StableWaifuComments/17783038",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 43,
    username: "Азизбек",
    characters: "Азизбек 3 Оба весьма сильные Богини, меняются формами, и оба получать от Ан",
    title: "Работа #43",
    image: "img/works/work_043.jpg",
    postLink: "https://t.me/StableWaifuComments/17782842",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 44,
    username: "Азизбек",
    characters: "Азизбек 2 Бородка у парня испортило композицию, но а так, прикольно",
    title: "Работа #44",
    image: "img/works/work_044.jpg",
    postLink: "https://t.me/StableWaifuComments/17782827",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 45,
    username: "Азизбек",
    characters: "Азизбек 2 Надо было написать, что порно должнл было быть красивым. Я немного офигела. увидев это",
    title: "Работа #45",
    image: "img/works/work_045.jpg",
    postLink: "https://t.me/StableWaifuComments/17782576",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 46,
    username: "@crystalloli",
    characters: "@DBcrimson 3 Иногда нажо выстрелить, что бы спасти других. Для врача, это очень тяжелое решение, но важное",
    title: "Работа #46",
    image: "img/works/work_046.jpg",
    postLink: "https://t.me/StableWaifuComments/17782549",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 47,
    username: "Азизбек",
    characters: "Азизбек 2 Какой такой, христианский вайб вышел, но работа простая",
    title: "Работа #47",
    image: "img/works/work_047.jpg",
    postLink: "https://t.me/StableWaifuComments/17782230",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 48,
    username: "Азизбек",
    characters: "@DBcrimson 3 И опять выстрел врача, но уже от главного. Она уже на примере других, знает, насколько важно быть решительной",
    title: "Работа #48",
    image: "img/works/work_048.jpg",
    postLink: "https://t.me/StableWaifuComments/17782180",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 49,
    username: "Азизбек",
    characters: "5 От этой работы аж дух захватило, насколько это нежно и сочно. Я в любви",
    title: "Работа #49",
    image: "img/works/work_049.jpg",
    postLink: "https://t.me/StableWaifuComments/17782133",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 50,
    username: "Азизбек",
    characters: "3 Сложно как то откоментировать, работу, но выглядит красиво",
    title: "Работа #50",
    image: "img/works/work_050.jpg",
    postLink: "https://t.me/StableWaifuComments/17781702",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 51,
    username: "Азизбек",
    characters: "3 Иногда хочется взять, и все бросить, но нет, если все бросить, все полетит в тартарары, и это надо исправлять, по пути ругая весь мир",
    title: "Работа #51",
    image: "img/works/work_051.jpg",
    postLink: "https://t.me/StableWaifuComments/17781506",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 52,
    username: "@macsheacaich",
    characters: "3 Меша, мне увы, не понравилась, но сама композиция, мое почтение",
    title: "Работа #52",
    image: "img/works/work_052.jpg",
    postLink: "https://t.me/StableWaifuComments/17781489",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 53,
    username: "Азизбек",
    characters: "4 В какой-то мере, это нежная и грустная работа. Она отлично передала суть персонажа",
    title: "Работа #53",
    image: "img/works/work_053.jpg",
    postLink: "https://t.me/StableWaifuComments/17781325",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 54,
    username: "Азизбек",
    characters: "5 Очень яркая работа, прям шикарно для такого жизнерадостного андроида.",
    title: "Работа #54",
    image: "img/works/work_054.jpg",
    postLink: "https://t.me/StableWaifuComments/17781225",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 55,
    username: "Азизбек",
    characters: "3 Не знаю кто, но я готова",
    title: "Работа #55",
    image: "img/works/work_055.jpg",
    postLink: "https://t.me/StableWaifuComments/17781189",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 56,
    username: "Азизбек",
    characters: "3 Довольно прикольная фреска",
    title: "Работа #56",
    image: "img/works/work_056.jpg",
    postLink: "https://t.me/StableWaifuComments/17781129",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 57,
    username: "Азизбек",
    characters: "4 Довольно нежный и милый секс, мне вкатило",
    title: "Работа #57",
    image: "img/works/work_057.jpg",
    postLink: "https://t.me/StableWaifuComments/17781086",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 58,
    username: "Азизбек",
    characters: "2 Прикольно, но не вкатило. Но Прикольно",
    title: "Работа #58",
    image: "img/works/work_058.jpg",
    postLink: "https://t.me/StableWaifuComments/17781065",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 59,
    username: "Азизбек",
    characters: "2 Хм, ну нормально в принципе",
    title: "Работа #59",
    image: "img/works/work_059.jpg",
    postLink: "https://t.me/StableWaifuComments/17781055",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 60,
    username: "Азизбек",
    characters: "3 Меша и правда хорошая, но хвост рука прям перекосоебило",
    title: "Работа #60",
    image: "img/works/work_060.jpg",
    postLink: "https://t.me/StableWaifuComments/17781035",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 61,
    username: "Азизбек",
    characters: "4 Хыххы, думаю, рыбка не будет против, что над ней так буду доминировать. Весы, весьма специфические.",
    title: "Работа #61",
    image: "img/works/work_061.jpg",
    postLink: "https://t.me/StableWaifuComments/17781033",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 62,
    username: "Азизбек",
    characters: "5 Страшно терять свой дом, где ты жил с самого его основания, потерять большую часть жителей, которых ты попросту не успел спасти. Но надо жить дальше с этой болью. Просто ради других, тех, кто остался",
    title: "Работа #62",
    image: "img/works/work_062.jpg",
    postLink: "https://t.me/StableWaifuComments/17781022",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 63,
    username: "Азизбек",
    characters: "4 Тут все прикольное, и поза, и композиция, и фон, все прям хорошо легло",
    title: "Работа #63",
    image: "img/works/work_063.jpg",
    postLink: "https://t.me/StableWaifuComments/17781019",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 64,
    username: "@yukidaruma8",
    characters: "2 Безумие и правда страшная вещь",
    title: "Работа #64",
    image: "img/works/work_064.jpg",
    postLink: "https://t.me/StableWaifuComments/17791211",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 65,
    username: "@forLansely",
    characters: "2 Зная Эриду, она бы не смутилась, а что нибудь выдала такое, от чего хоть стой, хоть падай",
    title: "Работа #65",
    image: "img/works/work_065.jpg",
    postLink: "https://t.me/StableWaifuComments/17792146",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 66,
    username: "@Bonja007",
    characters: "5 Восстановление природы из прошлого, хоть и в виде модели, и правда весьма тяжёлая, но завораживающая задача.",
    title: "Работа #66",
    image: "img/works/work_066.jpg",
    postLink: "https://t.me/StableWaifuComments/17804170",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 67,
    username: "@Bonja007",
    characters: "3 хлоп по попе",
    title: "Работа #67",
    image: "img/works/work_067.jpg",
    postLink: "https://t.me/StableWaifuComments/17804087?single",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 68,
    username: "@Bonja007",
    characters: "3 Хлоп по попеХ2",
    title: "Работа #68",
    image: "img/works/work_068.jpg",
    postLink: "https://t.me/StableWaifuComments/17804087?single",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 69,
    username: "@venera_chan",
    characters: "2 Мне не шибко понравилась ни меша, ни композиция. Да и увеличивать грудь персонажа было лишним",
    title: "Работа #69",
    image: "img/works/work_069.jpg",
    postLink: "https://t.me/StableWaifuComments/17803509",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 70,
    username: "@Erika_Demons_moon",
    characters: "3 К рабочему дню, он явно готов.",
    title: "Работа #70",
    image: "img/works/work_070.jpg",
    postLink: "https://t.me/StableWaifuComments/17799291",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 71,
    username: "@ShriMpik1",
    characters: "5 В эту работу, я тоже сразу влюбилась. Мне она очень понравилась, и то, как Изобилие привлекает к себе взор",
    title: "Работа #71",
    image: "img/works/work_071.jpg",
    postLink: "https://t.me/StableWaifuComments/17794516",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 72,
    username: "@ShriMpik1",
    characters: "2 Ну, такая одежда немного не про нее, хотя и выглядит прикольно. Вообще, она этакая момми",
    title: "Работа #72",
    image: "img/works/work_072.jpg",
    postLink: "https://t.me/StableWaifuComments/17794504",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 73,
    username: "@ShriMpik1",
    characters: "3 Интересно даже, кто тот счастливчик, который смог вытерпеть характер Лаг?",
    title: "Работа #73",
    image: "img/works/work_073.jpg",
    postLink: "https://t.me/StableWaifuComments/17794120",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 74,
    username: "@ianmaysky",
    characters: "5 Приятно просто войти в воду и поплавать в ней и расслабиться",
    title: "Работа #74",
    image: "img/works/work_074.jpg",
    postLink: "https://t.me/StableWaifuComments/17793682",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 75,
    username: "@forLansely",
    characters: "2 Изучение подводного мира всегда закатывает дух",
    title: "Работа #75",
    image: "img/works/work_075.jpg",
    postLink: "https://t.me/StableWaifuComments/17815223",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 76,
    username: "@ShriMpik1",
    characters: "5 Изучение неба, всегда захватывает дух людей, что в прошлом, что в нынешнем, что в будущем",
    title: "Работа #76",
    image: "img/works/work_076.jpg",
    postLink: "https://t.me/StableWaifuComments/17808703",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 77,
    username: "@Erika_Demons_moon",
    characters: "2 Эриду очень любит пугать других",
    title: "Работа #77",
    image: "img/works/work_077.jpg",
    postLink: "https://t.me/StableWaifuComments/17807362",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 78,
    username: "@forLansely",
    characters: "2 Ну, не думаю, что этот медик так следит за телом, хах. Вернее не качает его",
    title: "Работа #78",
    image: "img/works/work_078.jpg",
    postLink: "https://t.me/StableWaifuComments/17816404",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 79,
    username: "@forLansely",
    characters: "3 Ща кто-то лишится пальца",
    title: "Работа #79",
    image: "img/works/work_079.jpg",
    postLink: "https://t.me/StableWaifuComments/17817291",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 80,
    username: "@sseltraeh",
    characters: "2 слюнки тут уже лишние. Мне не особо зашло",
    title: "Работа #80",
    image: "img/works/work_080.jpg",
    postLink: "https://t.me/StableWaifuComments/17828408",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 81,
    username: "Азизбек",
    characters: "2 Ну, прикольно, но не вкатило, да, опять.",
    title: "Работа #81",
    image: "img/works/work_081.jpg",
    postLink: "https://t.me/StableWaifuComments/17827872",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 82,
    username: "@sseltraeh",
    characters: "2 Ну, тоже такое себе. Ан не шибко идёт атмосфера христианства и вампиризма",
    title: "Работа #82",
    image: "img/works/work_082.jpg",
    postLink: "https://t.me/StableWaifuComments/17827679",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 83,
    username: "@the_elv",
    characters: "3 Надо внимательно следить не только за небом, но и домом",
    title: "Работа #83",
    image: "img/works/work_083.jpg",
    postLink: "https://t.me/StableWaifuComments/17827035",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 84,
    username: "Азизбек",
    characters: "2 Хм, не думаю, что роботу в принципе надо есть человеческую пищу",
    title: "Работа #84",
    image: "img/works/work_084.jpg",
    postLink: "https://t.me/StableWaifuComments/17826671",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 85,
    username: "@the_elv",
    characters: "3 Приятно потратить время на плавание",
    title: "Работа #85",
    image: "img/works/work_085.jpg",
    postLink: "https://t.me/StableWaifuComments/17826605",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 86,
    username: "@the_elv",
    characters: "2 Ан так то выше, хоть и довольно тощая. Да и косы она не любит. В принципе, прикольно, не зашло",
    title: "Работа #86",
    image: "img/works/work_086.jpg",
    postLink: "https://t.me/StableWaifuComments/17826453",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 87,
    username: "@the_elv",
    characters: "2 Немного ткань все таки лишняя, или надо было сделать по другому",
    title: "Работа #87",
    image: "img/works/work_087.jpg",
    postLink: "https://t.me/StableWaifuComments/17826273",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 88,
    username: "@the_elv",
    characters: "4 Эриду мужчина, явно интересуется состояние \"зрителя\"",
    title: "Работа #88",
    image: "img/works/work_088.jpg",
    postLink: "https://t.me/StableWaifuComments/17826123",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 89,
    username: "@the_elv",
    characters: "5 вах-вах, Шикарная атмосфера вышла, да и само ханьфу красивое",
    title: "Работа #89",
    image: "img/works/work_089.jpg",
    postLink: "https://t.me/StableWaifuComments/17825788",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 90,
    username: "@the_elv",
    characters: "3 Когда ты случайно уронил важные бумаги и ты просто лёг, что бы не вспасть в истерику и просто полежать, дабы потом это всё убрать",
    title: "Работа #90",
    image: "img/works/work_090.jpg",
    postLink: "https://t.me/StableWaifuComments/17825537",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 91,
    username: "@sseltraeh",
    characters: "4 ой-ой, как тут все красиво и детализировано, мне понравилось",
    title: "Работа #91",
    image: "img/works/work_091.jpg",
    postLink: "https://t.me/StableWaifuComments/17825420",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 92,
    username: "@YormiFB",
    characters: "4 Северное сияние за окном, весьма красивое, да и сам партнёр уютный",
    title: "Работа #92",
    image: "img/works/work_092.jpg",
    postLink: "https://t.me/StableWaifuComments/17825375",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 93,
    username: "@sseltraeh",
    characters: "3 хах, на самом деле прикольное и нежное",
    title: "Работа #93",
    image: "img/works/work_093.jpg",
    postLink: "https://t.me/StableWaifuComments/17825182",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 94,
    username: "@forLansely",
    characters: "5 Очень красивая композиция. мне нравится. Явно на хороший лад настроен разговор",
    title: "Работа #94",
    image: "img/works/work_094.jpg",
    postLink: "https://t.me/StableWaifuComments/17824216",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 95,
    username: "@forLansely",
    characters: "2 Не хватает как по мне позы и динамики.",
    title: "Работа #95",
    image: "img/works/work_095.jpg",
    postLink: "https://t.me/StableWaifuComments/17824197",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 96,
    username: "@forLansely",
    characters: "3 Механическая, немного хоррорная атмосфера, розовое опят таки, динамика",
    title: "Работа #96",
    image: "img/works/work_096.jpg",
    postLink: "https://t.me/StableWaifuComments/17823866",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 97,
    username: "@sseltraeh",
    characters: "https://t.me/StableWaifuComments/17794120 👍 Арт принадлежит отправителю.",
    title: "Работа #97",
    image: "img/works/work_097.jpg",
    postLink: "https://t.me/StableWaifuComments/17823677",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 98,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17793682 👍 Арт принадлежит отправителю.",
    title: "Работа #98",
    image: "img/works/work_098.jpg",
    postLink: "https://t.me/StableWaifuComments/17823155",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 99,
    username: "@ianmaysky",
    characters: "https://t.me/StableWaifuComments/17815223 👍 Арт принадлежит отправителю.",
    title: "Работа #99",
    image: "img/works/work_099.jpg",
    postLink: "https://t.me/StableWaifuComments/17822406",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 100,
    username: "@alenxxz",
    characters: "https://t.me/StableWaifuComments/17808703 👍 Арт принадлежит отправителю.",
    title: "Работа #100",
    image: "img/works/work_100.jpg",
    postLink: "https://t.me/StableWaifuComments/17822151",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 101,
    username: "@alenxxz",
    characters: "https://t.me/StableWaifuComments/17807362 👍 Арт принадлежит отправителю.",
    title: "Работа #101",
    image: "img/works/work_101.jpg",
    postLink: "https://t.me/StableWaifuComments/17821839",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 102,
    username: "@Erika_Demons_moon",
    characters: "https://t.me/StableWaifuComments/17816404 👍 Арт принадлежит отправителю.",
    title: "Работа #102",
    image: "img/works/work_102.jpg",
    postLink: "https://t.me/StableWaifuComments/17821737",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 103,
    username: "@sseltraeh",
    characters: "https://t.me/StableWaifuComments/17817291 👍 Арт принадлежит отправителю.",
    title: "Работа #103",
    image: "img/works/work_103.jpg",
    postLink: "https://t.me/StableWaifuComments/17820899",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 104,
    username: "@sseltraeh",
    characters: "https://t.me/StableWaifuComments/17828408 👍 Арт принадлежит отправителю.",
    title: "Работа #104",
    image: "img/works/work_104.jpg",
    postLink: "https://t.me/StableWaifuComments/17820838",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 105,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17827872 👍 Арт принадлежит отправителю.",
    title: "Работа #105",
    image: "img/works/work_105.jpg",
    postLink: "https://t.me/StableWaifuComments/17820748",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 106,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17827679 👍 Арт принадлежит отправителю.",
    title: "Работа #106",
    image: "img/works/work_106.jpg",
    postLink: "https://t.me/StableWaifuComments/17820399",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 107,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17827035 👍 Арт принадлежит отправителю.",
    title: "Работа #107",
    image: "img/works/work_107.jpg",
    postLink: "https://t.me/StableWaifuComments/17819281",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 108,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17826671 👍 Арт принадлежит отправителю.",
    title: "Работа #108",
    image: "img/works/work_108.jpg",
    postLink: "https://t.me/StableWaifuComments/17819263",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 109,
    username: "@crystalloli",
    characters: "https://t.me/StableWaifuComments/17826605 👍 Арт принадлежит отправителю.",
    title: "Работа #109",
    image: "img/works/work_109.jpg",
    postLink: "https://t.me/StableWaifuComments/17819206",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 110,
    username: "@Erika_Demons_moon",
    characters: "https://t.me/StableWaifuComments/17826453 👍 Арт принадлежит отправителю.",
    title: "Работа #110",
    image: "img/works/work_110.jpg",
    postLink: "https://t.me/StableWaifuComments/17818964",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 111,
    username: "@forLansely",
    characters: "https://t.me/StableWaifuComments/17826273 👍 Арт принадлежит отправителю.",
    title: "Работа #111",
    image: "img/works/work_111.jpg",
    postLink: "https://t.me/StableWaifuComments/17828689",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 112,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17826123 👍 Арт принадлежит отправителю.",
    title: "Работа #112",
    image: "img/works/work_112.jpg",
    postLink: "https://t.me/StableWaifuComments/17828630",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 113,
    username: "@Elloree",
    characters: "https://t.me/StableWaifuComments/17825788 👍 Арт принадлежит отправителю.",
    title: "Работа #113",
    image: "img/works/work_113.jpg",
    postLink: "https://t.me/StableWaifuComments/17838542",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 114,
    username: "@forLansely",
    characters: "https://t.me/StableWaifuComments/17825537 👍 Арт принадлежит отправителю.",
    title: "Работа #114",
    image: "img/works/work_114.jpg",
    postLink: "https://t.me/StableWaifuComments/17836969",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 115,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17825420 👍 Арт принадлежит отправителю.",
    title: "Работа #115",
    image: "img/works/work_115.jpg",
    postLink: "https://t.me/StableWaifuComments/17836892",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 116,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17825375 👍 Арт принадлежит отправителю.",
    title: "Работа #116",
    image: "img/works/work_116.jpg",
    postLink: "https://t.me/StableWaifuComments/17836841",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 117,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17825182 👍 Арт принадлежит отправителю.",
    title: "Работа #117",
    image: "img/works/work_117.jpg",
    postLink: "https://t.me/StableWaifuComments/17836138",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 118,
    username: "@forLansely",
    characters: "https://t.me/StableWaifuComments/17824216 👍 Арт принадлежит отправителю.",
    title: "Работа #118",
    image: "img/works/work_118.jpg",
    postLink: "https://t.me/StableWaifuComments/17836130",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 119,
    username: "@forLansely",
    characters: "https://t.me/StableWaifuComments/17824197 👍 Арт принадлежит отправителю.",
    title: "Работа #119",
    image: "img/works/work_119.jpg",
    postLink: "https://t.me/StableWaifuComments/17836077",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 120,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17823866 👍 Арт принадлежит отправителю.",
    title: "Работа #120",
    image: "img/works/work_120.jpg",
    postLink: "https://t.me/StableWaifuComments/17835903",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 121,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17823677 👍 Арт принадлежит отправителю.",
    title: "Работа #121",
    image: "img/works/work_121.jpg",
    postLink: "https://t.me/StableWaifuComments/17835488",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 122,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17823155 👍 Арт принадлежит отправителю.",
    title: "Работа #122",
    image: "img/works/work_122.jpg",
    postLink: "https://t.me/StableWaifuComments/17835437",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 123,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17822406 👍 Арт принадлежит отправителю.",
    title: "Работа #123",
    image: "img/works/work_123.jpg",
    postLink: "https://t.me/StableWaifuComments/17835400",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 124,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17822151 👍 Арт принадлежит отправителю.",
    title: "Работа #124",
    image: "img/works/work_124.jpg",
    postLink: "https://t.me/StableWaifuComments/17835331",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 125,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17821839 👍 Арт принадлежит отправителю.",
    title: "Работа #125",
    image: "img/works/work_125.jpg",
    postLink: "https://t.me/StableWaifuComments/17835308",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 126,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17821737 👍 Арт принадлежит отправителю.",
    title: "Работа #126",
    image: "img/works/work_126.jpg",
    postLink: "https://t.me/StableWaifuComments/17835270",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 127,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17820899 👍 Арт принадлежит отправителю.",
    title: "Работа #127",
    image: "img/works/work_127.jpg",
    postLink: "https://t.me/StableWaifuComments/17835259",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 128,
    username: "AnVpAr",
    characters: "https://t.me/StableWaifuComments/17820838 👍 Арт принадлежит отправителю.",
    title: "Работа #128",
    image: "img/works/work_128.jpg",
    postLink: "https://t.me/StableWaifuComments/17835206",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 129,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17820748 👍 Арт принадлежит отправителю.",
    title: "Работа #129",
    image: "img/works/work_129.jpg",
    postLink: "https://t.me/StableWaifuComments/17835152",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 130,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17820399 👍 Арт принадлежит отправителю.",
    title: "Работа #130",
    image: "img/works/work_130.jpg",
    postLink: "https://t.me/StableWaifuComments/17835097",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 131,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17819281 👍 Арт принадлежит отправителю.",
    title: "Работа #131",
    image: "img/works/work_131.jpg",
    postLink: "https://t.me/StableWaifuComments/17834695",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 132,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17819263 👍 Арт принадлежит отправителю.",
    title: "Работа #132",
    image: "img/works/work_132.jpg",
    postLink: "https://t.me/StableWaifuComments/17834550",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 133,
    username: "Азизбек",
    characters: "https://t.me/StableWaifuComments/17819206 👍 Арт принадлежит отправителю.",
    title: "Работа #133",
    image: "img/works/work_133.jpg",
    postLink: "https://t.me/StableWaifuComments/17834441",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 134,
    username: "@sseltraeh",
    characters: "https://t.me/StableWaifuComments/17818964 👍 Арт принадлежит отправителю.",
    title: "Работа #134",
    image: "img/works/work_134.jpg",
    postLink: "https://t.me/StableWaifuComments/17834382",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 135,
    username: "@alenxxz",
    characters: "https://t.me/StableWaifuComments/17828689 👍 Арт принадлежит отправителю.",
    title: "Работа #135",
    image: "img/works/work_135.jpg",
    postLink: "https://t.me/StableWaifuComments/17834145",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 136,
    username: "@Erika_Demons_moon",
    characters: "https://t.me/StableWaifuComments/17828630 👍 Арт принадлежит отправителю.",
    title: "Работа #136",
    image: "img/works/work_136.jpg",
    postLink: "https://t.me/StableWaifuComments/17833907",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 137,
    username: "@Nunasw",
    characters: "https://t.me/StableWaifuComments/17838542 👍 Арт принадлежит отправителю.",
    title: "Работа #137",
    image: "img/works/work_137.jpg",
    postLink: "https://t.me/StableWaifuComments/17832732",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 138,
    username: "@Nunasw",
    characters: "https://t.me/StableWaifuComments/17836969 👍 Арт принадлежит отправителю.",
    title: "Работа #138",
    image: "img/works/work_138.jpg",
    postLink: "https://t.me/StableWaifuComments/17832098",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 139,
    username: "@Nunasw",
    characters: "https://t.me/StableWaifuComments/17836892 👍 Арт принадлежит отправителю.",
    title: "Работа #139",
    image: "img/works/work_139.jpg",
    postLink: "https://t.me/StableWaifuComments/17831609",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 140,
    username: "@Erika_Demons_moon",
    characters: "https://t.me/StableWaifuComments/17836841 👍 Арт принадлежит отправителю.",
    title: "Работа #140",
    image: "img/works/work_140.jpg",
    postLink: "https://t.me/StableWaifuComments/17851265",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 141,
    username: "@DablinElkiPalki",
    characters: "https://t.me/StableWaifuComments/17836138 👍 Арт принадлежит отправителю.",
    title: "Работа #141",
    image: "img/works/work_141.jpg",
    postLink: "https://t.me/StableWaifuComments/17851033",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 142,
    username: "@Erika_Demons_moon",
    characters: "https://t.me/StableWaifuComments/17836130 👍 Арт принадлежит отправителю.",
    title: "Работа #142",
    image: "img/works/work_142.jpg",
    postLink: "https://t.me/StableWaifuComments/17850796",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 143,
    username: "@Erika_Demons_moon",
    characters: "https://t.me/StableWaifuComments/17836077 👍 Арт принадлежит отправителю.",
    title: "Работа #143",
    image: "img/works/work_143.jpg",
    postLink: "https://t.me/StableWaifuComments/17850715",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 144,
    username: "@DablinElkiPalki",
    characters: "https://t.me/StableWaifuComments/17835903 👍 Арт принадлежит отправителю.",
    title: "Работа #144",
    image: "img/works/work_144.jpg",
    postLink: "https://t.me/StableWaifuComments/17850441",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 145,
    username: "@Erika_Demons_moon",
    characters: "",
    title: "Работа #145",
    image: "img/works/work_145.jpg",
    postLink: "https://t.me/StableWaifuComments/17850313",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 146,
    username: "@DablinElkiPalki",
    characters: "",
    title: "Работа #146",
    image: "img/works/work_146.jpg",
    postLink: "https://t.me/StableWaifuComments/17851373",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 147,
    username: "@Erika_Demons_moon",
    characters: "",
    title: "Работа #147",
    image: "img/works/work_147.jpg",
    postLink: "https://t.me/StableWaifuComments/17850264",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 148,
    username: "@ayanamiurey",
    characters: "",
    title: "Работа #148",
    image: "img/works/work_148.jpg",
    postLink: "https://t.me/StableWaifuComments/17849653",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 149,
    username: "Азизбек",
    characters: "",
    title: "Работа #149",
    image: "img/works/work_149.jpg",
    postLink: "https://t.me/StableWaifuComments/17849605",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 150,
    username: "@Rina_ds",
    characters: "",
    title: "Работа #150",
    image: "img/works/work_150.jpg",
    postLink: "https://t.me/StableWaifuComments/17849579",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 151,
    username: "@kazeivaa",
    characters: "",
    title: "Работа #151",
    image: "img/works/work_151.jpg",
    postLink: "https://t.me/StableWaifuComments/17851508",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 152,
    username: "@Rina_ds",
    characters: "",
    title: "Работа #152",
    image: "img/works/work_152.jpg",
    postLink: "https://t.me/StableWaifuComments/17849561",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 153,
    username: "@Rina_ds",
    characters: "",
    title: "Работа #153",
    image: "img/works/work_153.jpg",
    postLink: "https://t.me/StableWaifuComments/17849546",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 154,
    username: "Азизбек",
    characters: "",
    title: "Работа #154",
    image: "img/works/work_154.jpg",
    postLink: "https://t.me/StableWaifuComments/17849131",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 155,
    username: "@ayanamiurey",
    characters: "",
    title: "Работа #155",
    image: "img/works/work_155.jpg",
    postLink: "https://t.me/StableWaifuComments/17848948",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 156,
    username: "@forLansely",
    characters: "",
    title: "Работа #156",
    image: "img/works/work_156.jpg",
    postLink: "https://t.me/StableWaifuComments/17848726",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 157,
    username: "Азизбек",
    characters: "",
    title: "Работа #157",
    image: "img/works/work_157.jpg",
    postLink: "https://t.me/StableWaifuComments/17848539",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 158,
    username: "@alenxxz",
    characters: "",
    title: "Работа #158",
    image: "img/works/work_158.jpg",
    postLink: "https://t.me/StableWaifuComments/17848362",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 159,
    username: "@yukidaruma8",
    characters: "",
    title: "Работа #159",
    image: "img/works/work_159.jpg",
    postLink: "https://t.me/StableWaifuComments/17848324",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 160,
    username: "@aistenokd",
    characters: "",
    title: "Работа #160",
    image: "img/works/work_160.jpg",
    postLink: "https://t.me/StableWaifuComments/17851690",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 161,
    username: "@Erika_Demons_moon",
    characters: "",
    title: "Работа #161",
    image: "img/works/work_161.jpg",
    postLink: "https://t.me/StableWaifuComments/17848112",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 162,
    username: "@Erika_Demons_moon",
    characters: "",
    title: "Работа #162",
    image: "img/works/work_162.jpg",
    postLink: "https://t.me/StableWaifuComments/17848054",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 163,
    username: "@Elloree",
    characters: "",
    title: "Работа #163",
    image: "img/works/work_163.jpg",
    postLink: "https://t.me/StableWaifuComments/17848044",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 164,
    username: "@DablinElkiPalki",
    characters: "",
    title: "Работа #164",
    image: "img/works/work_164.jpg",
    postLink: "https://t.me/StableWaifuComments/17851758",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 165,
    username: "",
    characters: "",
    title: "Работа #165",
    image: "img/works/work_165.jpg",
    postLink: "https://t.me/StableWaifuComments/17847989",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 166,
    username: "@Erika_Demons_moon",
    characters: "",
    title: "Работа #166",
    image: "img/works/work_166.jpg",
    postLink: "https://t.me/StableWaifuComments/17847963",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 167,
    username: "@vivka_wuu",
    characters: "",
    title: "Работа #167",
    image: "img/works/work_167.jpg",
    postLink: "https://t.me/StableWaifuComments/17847379",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 168,
    username: "@the_elv",
    characters: "",
    title: "Работа #168",
    image: "img/works/work_168.jpg",
    postLink: "https://t.me/StableWaifuComments/17846952",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 169,
    username: "@alenxxz",
    characters: "",
    title: "Работа #169",
    image: "img/works/work_169.jpg",
    postLink: "https://t.me/StableWaifuComments/17846785",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 170,
    username: "@Tabayume",
    characters: "",
    title: "Работа #170",
    image: "img/works/work_170.jpg",
    postLink: "https://t.me/StableWaifuComments/17846482",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 171,
    username: "@Tabayume",
    characters: "",
    title: "Работа #171",
    image: "img/works/work_171.jpg",
    postLink: "https://t.me/StableWaifuComments/17846475",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 172,
    username: "Азизбек",
    characters: "",
    title: "Работа #172",
    image: "img/works/work_172.jpg",
    postLink: "https://t.me/StableWaifuComments/17846465",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 173,
    username: "Азизбек",
    characters: "",
    title: "Работа #173",
    image: "img/works/work_173.jpg",
    postLink: "https://t.me/StableWaifuComments/17846426",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 174,
    username: "Азизбек",
    characters: "",
    title: "Работа #174",
    image: "img/works/work_174.jpg",
    postLink: "https://t.me/StableWaifuComments/17846388",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 175,
    username: "@ayanamiurey",
    characters: "",
    title: "Работа #175",
    image: "img/works/work_175.jpg",
    postLink: "https://t.me/StableWaifuComments/17846212",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 176,
    username: "@ayanamiurey",
    characters: "",
    title: "Работа #176",
    image: "img/works/work_176.jpg",
    postLink: "https://t.me/StableWaifuComments/17845764",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 177,
    username: "Peachu ~",
    characters: "",
    title: "Работа #177",
    image: "img/works/work_177.jpg",
    postLink: "https://t.me/StableWaifuComments/17845587",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 178,
    username: "@journalistdeer",
    characters: "",
    title: "Работа #178",
    image: "img/works/work_178.jpg",
    postLink: "https://t.me/StableWaifuComments/17845437",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 179,
    username: "@ianmaysky",
    characters: "",
    title: "Работа #179",
    image: "img/works/work_179.jpg",
    postLink: "https://t.me/StableWaifuComments/17845384",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 180,
    username: "@Bonja007",
    characters: "",
    title: "Работа #180",
    image: "img/works/work_180.jpg",
    postLink: "https://t.me/StableWaifuComments/17845306",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 181,
    username: "@journalistdeer",
    characters: "",
    title: "Работа #181",
    image: "img/works/work_181.jpg",
    postLink: "https://t.me/StableWaifuComments/17845256",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 182,
    username: "@Bonja007",
    characters: "",
    title: "Работа #182",
    image: "img/works/work_182.jpg",
    postLink: "https://t.me/StableWaifuComments/17845119",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 183,
    username: "@journalistdeer",
    characters: "",
    title: "Работа #183",
    image: "img/works/work_183.jpg",
    postLink: "https://t.me/StableWaifuComments/17845099",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 184,
    username: "@Bonja007",
    characters: "",
    title: "Работа #184",
    image: "img/works/work_184.jpg",
    postLink: "https://t.me/StableWaifuComments/17844954",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 185,
    username: "@journalistdeer",
    characters: "",
    title: "Работа #185",
    image: "img/works/work_185.jpg",
    postLink: "https://t.me/StableWaifuComments/17844966",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 186,
    username: "@Bonja007",
    characters: "",
    title: "Работа #186",
    image: "img/works/work_186.jpg",
    postLink: "https://t.me/StableWaifuComments/17844901",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 187,
    username: "@kazeivaa",
    characters: "",
    title: "Работа #187",
    image: "img/works/work_187.jpg",
    postLink: "https://t.me/StableWaifuComments/17844771",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 188,
    username: "@kazeivaa",
    characters: "",
    title: "Работа #188",
    image: "img/works/work_188.jpg",
    postLink: "https://t.me/StableWaifuComments/17844673",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 189,
    username: "@kazeivaa",
    characters: "",
    title: "Работа #189",
    image: "img/works/work_189.jpg",
    postLink: "https://t.me/StableWaifuComments/17844609",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: ""
  },
  {
    id: 190,
    username: "@Bonja007",
    characters: "",
    title: "Работа #190",
    image: "img/works/work_190.jpg",
    postLink: "https://t.me/StableWaifuComments/17844554",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: ""
  },
  {
    id: 191,
    username: "@desu_chaan",
    characters: "",
    title: "Работа #191",
    image: "img/works/work_191.jpg",
    postLink: "https://t.me/StableWaifuComments/17843950",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: ""
  },
  {
    id: 192,
    username: "@desu_chaan",
    characters: "",
    title: "Работа #192",
    image: "img/works/work_192.jpg",
    postLink: "https://t.me/StableWaifuComments/17843920",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: ""
  },
  {
    id: 193,
    username: "@desu_chaan",
    characters: "",
    title: "Работа #193",
    image: "img/works/work_193.jpg",
    postLink: "https://t.me/StableWaifuComments/17843900",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: "Как я и говорила, я очень люблю работы с пшеничным полем. очень красиво и романтично"
  },
  {
    id: 194,
    username: "@desu_chaan",
    characters: "",
    title: "Работа #194",
    image: "img/works/work_194.jpg",
    postLink: "https://t.me/StableWaifuComments/17843881",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: "Изобилие тоже любит почитать, где нибудь там, проездом"
  },
  {
    id: 195,
    username: "@desu_chaan",
    characters: "",
    title: "Работа #195",
    image: "img/works/work_195.jpg",
    postLink: "https://t.me/StableWaifuComments/17843822",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: "Простая, но динамичная"
  },
  {
    id: 196,
    username: "@Erika_Demons_moon",
    characters: "",
    title: "Работа #196",
    image: "img/works/work_196.jpg",
    postLink: "https://t.me/StableWaifuComments/17842646",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: "оо, выглядит весьма красиво. Мне нравится, как все смотрится"
  },
  {
    id: 197,
    username: "Азизбек",
    characters: "",
    title: "Работа #197",
    image: "img/works/work_197.jpg",
    postLink: "https://t.me/StableWaifuComments/17842641",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: "Выглядит красиво, прям очень хорошо, я довольна"
  },
  {
    id: 198,
    username: "@Erika_Demons_moon",
    characters: "",
    title: "Работа #198",
    image: "img/works/work_198.jpg",
    postLink: "https://t.me/StableWaifuComments/17842633",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: "Прекрасная с Касом, более нечего сказать"
  },
  {
    id: 199,
    username: "Азизбек",
    characters: "",
    title: "Работа #199",
    image: "img/works/work_199.jpg",
    postLink: "https://t.me/StableWaifuComments/17842010",
    score: 4,
    scoreMax: 5,
    scoreRaw: 4,
    place: 2,
    reward: 100,
    isWinner: true,
    awardTitle: "2 место",
    comment: "хм, а вкдт красиво выглядит, мне понравилось"
  },
  {
    id: 200,
    username: "Азизбек",
    characters: "",
    title: "Работа #200",
    image: "img/works/work_200.jpg",
    postLink: "https://t.me/StableWaifuComments/17841915",
    score: 2,
    scoreMax: 5,
    scoreRaw: 2,
    place: 0,
    reward: 0,
    isWinner: false,
    awardTitle: "",
    comment: "Н-да, вот тебе и социализация"
  },
  {
    id: 201,
    username: "Азизбек",
    characters: "",
    title: "Работа #201",
    image: "img/works/work_201.jpg",
    postLink: "https://t.me/StableWaifuComments/17841882",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: "Хм, ну прикольно выглядит. призывает демона, который не будет от нее пугаться"
  },
  {
    id: 202,
    username: "Азизбек",
    characters: "",
    title: "Работа #202",
    image: "img/works/work_202.jpg",
    postLink: "https://t.me/StableWaifuComments/17841834",
    score: 3,
    scoreMax: 5,
    scoreRaw: 3,
    place: 3,
    reward: 50,
    isWinner: true,
    awardTitle: "3 место",
    comment: "Купание в крови продлевает жизнь?"
  },
  {
    id: 203,
    username: "@sseltraeh",
    characters: "",
    title: "Работа #203",
    image: "img/works/work_203.jpg",
    postLink: "https://t.me/StableWaifuComments/17841108",
    score: 5,
    scoreMax: 5,
    scoreRaw: 5,
    place: 1,
    reward: 300,
    isWinner: true,
    awardTitle: "1 место",
    comment: "уютная атмосфера на самом деле. Очень приятно смотреть на эту работу"
  }
];
